apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx # Will get all pods that are named with app nginx
  template: # content pod that we have
    metadata:
      labels: # is not mandatory but it`s used to internal search
        app: nginx
    spec: # specific all into pod.
      containers:
        - name: nginx
          image: nginx:latest
          resources: # all resource that will have
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: mypvc