apiVersion: v1 # api version
kind: Pod # pod type
metadata:
  name: nginx # pod name
  labels: # lable is not mandatory
    name: nginx
spec: # espcific all to have into in the pod
  containers: # specific all to have into the container
  - name: nginx
    image: nginx:latest
    resources: # how much resource the pod will have, is not mandatory
      # limits:
        # memory: "128Mi"
        # cpu: "500m"
    ports:
     - containerPort: 80 # nginx port
