apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem # it is not mandatory in clound service
  accessModes:
    - ReadWriteOnce
