apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # type: LoadBalancer # it is not mandatory, visible to internet
  selector:
    app: nginx # filter all pods that named with app nginx
  ports:
  - port: 80 # service port
    targetPort: 80 # direction container port
